apiVersion: v1
kind: Namespace
metadata:
  name: jarvis-system
  labels:
    name: jarvis-system
    app: jarvis
    environment: production
---
apiVersion: v1
kind: Secret
metadata:
  name: jarvis-secrets
  namespace: jarvis-system
  labels:
    app: jarvis
    component: secrets
type: Opaque
data:
  # Base64 encoded secrets (replace with actual values)
  api-key: <BASE64_ENCODED_API_KEY>
  database-password: <BASE64_ENCODED_DB_PASSWORD>
  encryption-key: <BASE64_ENCODED_ENCRYPTION_KEY>
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: jarvis-system
  name: jarvis-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jarvis-role-binding
  namespace: jarvis-system
subjects:
- kind: ServiceAccount
  name: default
  namespace: jarvis-system
roleRef:
  kind: Role
  name: jarvis-role
  apiGroup: rbac.authorization.k8s.io